description: finetune_videollama2_mamba_batch1_stream_epoch15_8a100_gradient_accumulation_steps2_only_trainllm_124_lastckpt26445_allframe_pastcaption_2e6_1211_4a100

target:
  service: sing
  name: whitney13
  workspace_name: srgxws

environment:
  image: amlt-sing/acpt-torch2.4.1-py3.10-cuda12.4-ubuntu22.04
  setup:
    - sudo apt-get install -y  libglib2.0-0

storage:
  input:
    storage_account_name: sanbpx4p3idss6q   # TODO!!
    container_name: v-dingxin  # TODO!!
    mount_dir: /mnt/input/

  # output:
  #   storage_account_name: sanbpx4p3idss6q
  #   container_name: v-dingxin
  #   mount_dir: /home/v-dingxin/blob
  #   is_output: True

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: /home/v-dingxin/videollama2_plus-main   #TODO!!

jobs:
  - name: finetune_videollama2_mamba_batch1_stream_epoch15_8a100_gradient_accumulation_steps2_only_trainllm_124_lastckpt26445_allframe_pastcaption_2e6_1211_4a100
    sku: 80G4-A100
    command:
    - pip install decord
    - pip install -r require_yizhao.txt
    - pip install flash-attn==2.6.1 --no-build-isolation
    - pip install transformers==4.44.2
    - pip install mamba_ssm
    - pip install timm
    - pip install lightning
    - pip install accelerate
    - pip install scikit-image
    - pip install moviepy==1.0.3 --user
    - pip install scenedetect==0.6.3
    - pip install wandb==0.18.3
    - pip install ftfy regex Pillow opencv-python timm==0.6.12 einops fvcore
    - pip install tensorboard -U
    - torchrun --nproc_per_node=4 --node_rank 0 videollama2/train_flash_attn_score.py
        --output_dir /mnt/input/finetune_videollama2_mamba_batch1_stream_epoch15_8a100_gradient_accumulation_steps2_only_trainllm_124_lastckpt26445_allframe_pastcaption_2e6_1211_4a100
        --deepspeed scripts/zero2_yizhao.json
        --version v1_mistral
        --score_dataset True
        --score_dataset_train_cls True
        --vision_tower /mnt/input/clip-vit-large-patch14-336
        --freeze_backbone False
        --mm_projector_type mamba
        --model_name_or_path /mnt/input/finetune_videollama2_mamba_batch1_stream_epoch15_8a100_gradient_accumulation_steps2_only_trainllm_124/checkpoint-26445
        --data_path  /mnt/input/video_llm/datasets/videollava_pt/valley_llavaimage_new.json
        --data_folder /mnt/input/video_llm/datasets/videollava_pt
        --mm_vision_select_layer -2
        --mm_use_im_start_end False
        --mm_use_im_patch_token False
        --image_aspect_ratio pad
        --num_frames 32
        --bf16 True
        --tf32 True
        --fp16 False
        --num_train_epochs 15
        --per_device_train_batch_size 1
        --per_device_eval_batch_size 4
        --gradient_accumulation_steps 2
        --evaluation_strategy "no"
        --save_strategy "steps"
        --save_steps 5000
        --save_total_limit 99
        --learning_rate 2e-6
        --weight_decay 0.
        --warmup_ratio 0.03
        --lr_scheduler_type "cosine"
        --logging_steps 1
        --model_max_length 20480
        --gradient_checkpointing True
        --dataloader_num_workers 8
        --report_to wandb
        --run_name finetune_videollama2_mamba_batch1_stream_epoch15_8a100_gradient_accumulation_steps2_only_trainllm_124_lastckpt26445_allframe_pastcaption_2e6_1211_4a100
    identity: managed
    submit_args:
      env:
        WANDB_API_KEY: 'c2814c78978395e25bb69a6d987a233e8b0f076f'
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/e546c811-2312-46e2-9fd0-c949c65da4d9/resourcegroups/srgx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/srgxuai
    sla_tier: premium
    execution_mode: basic 
    priority: high