description: finetune_videollama2_mamba_batch1_stream_epoch15_ego4d_only_trainllm_1230_new_parallel_sample_resume_ck450_cls_2e6_focalloss_015_lastframe_ckpt440_eval_cls

target:
  service: sing
  name: msroctobasicvc
  workspace_name: srgxws

environment:
  image: amlt-sing/acpt-rocm6.1_ubuntu20.04_py3.9_pytorch2.1.2 
  setup:
    - pip install azureml-mlflow tensorboard --user
    - sudo apt-get update
    - sudo apt-get install -y htop ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
    - pip install --no-cache-dir --upgrade pip wheel

storage:
  input:
    storage_account_name: sanbpx4p3idss6q   # TODO!!
    container_name: v-dingxin  # TODO!!
    mount_dir: /mnt/input/

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: /home/v-dingxin/videollama2_plus-main   #TODO!!

jobs:
  - name: finetune_videollama2_mamba_batch1_stream_epoch15_ego4d_only_trainllm_1230_new_parallel_sample_resume_ck450_cls_2e6_focalloss_015_lastframe_ckpt440_eval_cls
    sku: 192G8-MI300X-IB-xGMI
    command:
    - pip install decord
    - pip install -r require_yizhao.txt
    - pip install transformers==4.44.2
    - pip install timm
    - pip install lightning
    - pip install accelerate
    - pip install scikit-image
    - pip install moviepy==1.0.3 --user
    - pip install scenedetect==0.6.3
    - pip install wandb==0.18.3
    - pip install ftfy regex Pillow opencv-python timm==0.6.12 einops fvcore
    - git clone https://github.com/state-spaces/mamba.git
    - cd mamba 
    - pip install . --no-build-isolation
    - cd ..
    - git clone https://github.com/Dao-AILab/flash-attention.git
    - cd flash-attention
    - git checkout 418d677192b483dfc1decfdf9aadca40b402485d  # v2.6.3
    - BUILD_TARGET=rocm python setup.py install
    - cd ..
    - pip install pycocoevalcap
    - pip install SentencePiece
    - pip install editdistance
    - pip install Levenshtein
    - sudo apt-get install openjdk-8-jdk
    - ROCR_VISIBLE_DEVICES=0 python videollama2/eval/inference_video_ego4d_stream_parallel_new.py
      --model-path /mnt/input/finetune_videollama2_mamba_batch1_stream_epoch15_ego4d_only_trainllm_1230_new_parallel_sample_resume_ck450_cls_2e6_focalloss_015_lastframe/checkpoint-440
      --caption-path /mnt/input/finetune_videollama2_mamba_batch1_stream_epoch15_ego4d_only_trainllm_1230_new_parallel_sample_resume_ck450_cls_2e6_focalloss_015_lastframe/checkpoint-440/caption/ours_caption.csv
      --model-name videollama_mamba-finetune
      --eval-caption True
      --cur_fps 2
      --num-workers 16
      --ego4d_dataset
      --eval_type cls
      --sample_per 0.3
      --sample_type log2
    identity: managed
    submit_args:
      env:
        WANDB_API_KEY: 'c2814c78978395e25bb69a6d987a233e8b0f076f'
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/e546c811-2312-46e2-9fd0-c949c65da4d9/resourcegroups/srgx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/srgxuai
    sla_tier: Standard
    execution_mode: basic 
    priority: high